/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/dev/oceanRubble2.glb -s -T 
Files: public/dev/oceanRubble2.glb [885.06KB] > D:\Web_Projects\Games\diver-debby\oceanRubble2-transformed.glb [274.48KB] (69%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/oceanRubble2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.mesh.geometry} material={materials.base_material} rotation={[Math.PI / 2, 0, 0]} scale={2.211} />
    </group>
  )
}

useGLTF.preload('/oceanRubble2-transformed.glb')
