/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/dev/seaMine.glb -s -T 
Files: public/dev/seaMine.glb [752.12KB] > D:\Web_Projects\Games\diver-debby\seaMine-transformed.glb [228.1KB] (70%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/seaMine-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.mesh.geometry} material={materials.base_material} rotation={[Math.PI / 2, 0, 0]} scale={1.881} />
    </group>
  )
}

useGLTF.preload('/seaMine-transformed.glb')
