/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/dev/shark.glb -s -T 
Files: public/dev/shark.glb [497.26KB] > D:\Web_Projects\Games\diver-debby\shark-transformed.glb [119.34KB] (76%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/shark-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.mesh.geometry} material={materials.base_material} rotation={[Math.PI / 2, 0, 0]} scale={1.663} />
    </group>
  )
}

useGLTF.preload('/shark-transformed.glb')
